(setq xah-fly-use-control-key nil)

(defun xav-append-copy-line-or-region ()
  (interactive)
  (append-next-kill)
  (if (use-region-p)
      ()
    (kill-append "\n" nil))
  (xah-copy-line-or-region)
  )

(defun xav-append-cut-line-or-region ()
  (interactive)
  (append-next-kill)
  (if (use-region-p)
      ()
    (kill-append "\n" nil))
  (xah-cut-line-or-region)
  )

(defun xah-copy-dir-path ()
  (interactive)
  (xah-copy-file-path t)
  )
(define-key xah-fly-c-keymap (kbd "M-i") 'split-window-vertically)
(define-key xah-fly-c-keymap (kbd "M-k") 'split-window-vertically)
(define-key xah-fly-c-keymap (kbd "M-j") 'split-window-horizontally)
(define-key xah-fly-c-keymap (kbd "M-l") 'split-window-horizontally)
(define-key xah-fly-c-keymap (kbd "r") 'isearch-forward-regexp)

(define-key xah-fly-t-keymap "y" 'xah-query-replace-current-word)

(define-key xah-fly-leader-key-map (kbd "M-i") 'delete-window-up)
(define-key xah-fly-leader-key-map (kbd "M-k") 'delete-window-down)
(define-key xah-fly-leader-key-map (kbd "M-j") 'delete-window-left)
(define-key xah-fly-leader-key-map (kbd "M-l") 'delete-window-right)
(define-key xah-fly-leader-key-map (kbd "+") 'org-agenda)

(define-key xah-fly-leader-key-map (kbd "RET") 'newline)
(define-key xah-fly-leader-key-map (kbd "<return>") 'newline)

(provide 'extra2)
